#!/usr/bin/env bash

invalid_input() {
  echo "Input contains invalid chars"
  exit 1
}

execute_script() {
  [[ "${1}" =~ [^a-zA-Z0-9] ]] && invalid_input

  script="$HOME/.config/sshtui/scripts/${1}"
  [[ -x "${script}" ]] && ${script}

  exit 0
}

sshtui() {
  [[ -f $(which fzf) ]] || exit 1
  [[ -f $(which bat) ]] || exit 1
  [[ -f $(which awk) ]] || exit 1

  HOST=$(grep -R -e "^Host " ~/.ssh/config.d/ | awk '{print $2}' | tv --preview-command "awk '/{}/' RS= ~/.ssh/config.d/* | bat -l ssh_config --color=always --style=grid --line-range :300")
  if [ -z "$HOST" ]; then
    return
  fi

  echo "SSH session started, connecting to $HOST"
  ssh "$HOST"
}

[[ "$#" -ne 0 ]] && execute_script "$1"

sshtui
